---
abstract: 'Convert a Tree::DAG_Node object into the HTML and JS for a YUI3 menu'
author:
  - 'Ron Savage <ron@savage.net.au>'
build_requires:
  Test::More: 0.94
  Test::Pod: 1.44
configure_requires:
  Module::Build: 0.38
dynamic_config: 1
generated_by: 'Module::Build version 0.38, CPAN::Meta::Converter version 2.110580'
license: artistic
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: HTML-YUI3-Menu
provides:
  HTML::YUI3::Menu:
    file: lib/HTML/YUI3/Menu.pm
    version: 1.01
  HTML::YUI3::Menu::Util::Config:
    file: lib/HTML/YUI3/Menu/Util/Config.pm
    version: 1.01
requires:
  Config::Tiny: 2.13
  File::Copy: 2.18
  File::HomeDir: 0.97
  Hash::FieldHash: 0.1
  Path::Class: 0.23
  Text::Xslate: 1.0007
resources:
  license: http://opensource.org/licenses/artistic-license.php
version: 1.01
